### PR TITLE
Bugfix in getUpdatedCaretPos method

### PR DESCRIPTION
**Pull request by wolfy75**
Cursor was not moved to the next position after typing the same value at the given digit

### CODE REVIEW

**Comment by shogogan** [comment]
I think that #5  fixed this issue already (yet i'll verify)

**Comment by shogogan** [comment]
yep, it should work on the racoon-mask-primeng version 1.1.9 (if using the primeng, the base and full needs some work by now, so it is outdated)

**Comment by wolfy75** [comment]
I tried it with the mentioned version and it did not work for me.

**Comment by shogogan** [comment]
Strange, could you simulate it on the stackblitz?

**Comment by shogogan** [comment]
oh, found it why it didn't work (was testing only with the last character --', totally my bad), would merge your pull request but you deleted the repository :(
But will add a new version ASAP

Try with 1.1.10 (just did your pull and worked. if you want to open the PR again to put your name on the commit, just say it :) )

**Comment by wolfy75** [comment]
Okay, I can create the PR again soon :)

**Comment by wolfy75** [comment]
My name is not so important :) I can check it only tomorrow, but I am sure it will be fine. Thanks for the fix!

**Pull request closed without merging**
